version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379"

  sentiment-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: socket-server
    depends_on:
      - redis
    ports:
      - "5001:5001"
    volumes:
      - ./app:/app
      - ./app/models:/app/models
    command: python server.py

  sentiment-worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - ./app:/app
      - ./app/models:/app/models
    command: python worker.py
    deploy:
      replicas: 4  # Chạy 4 worker instances