version: '3.8'

services:
  inference-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inference-server
    restart: always

  sentiment-sentiment:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    command: python socket_server.py
    restart: always